config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions , :portfolios , :contacts

  resources :blogs do
    match '/comments/:id/approve' => 'comments#approve', :as => :approve , via: [:get, :post]
    match '/comments/:id/delete' => 'comments#destroy', via: [:get,:delete]
    resources :comments
  end

  match '/login' => "user_sessions#new",      :as => :login , via: [:get, :post]
  match '/logout' => "user_sessions#destroy", :as => :logout , via: [:get, :post]
  match '/about_us' => 'dashboard#about_us', :as => :about_us , via: [:get, :post]
  match '/homepage' => 'dashboard#homepage', :as => :homepage , via: [:get, :post]
  match '/portfolios/:id/delete' => 'portfolios#destroy', via: [:get]
  match '/blogs/:id/delete' => 'blogs#destroy', via: [:get,:delete]

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup, via: [:get, :post]

  root :to => 'dashboard#homepage'

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true
	validates :url, presence: true
	has_attached_file :portfolio_image, styles: { medium: "220x210>", thumb: "85x80>", natural: "360x206", small: "80x80", large: "700x600" }
    validates_attachment_content_type :portfolio_image, content_type: /\Aimage\/.*\Z/
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :require_user, :only => [:show, :edit, :update]
  
  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      flash[:notice] = "Portfolio saved successfully...!"
      redirect_to portfolios_path
    else
      flash[:notice] = "There was a problem saving portfolio."
      
    end
  end

  def index
    @portfolios = Portfolio.all
    @portfolios = Portfolio.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    @portfolio.update(portfolio_params)
    redirect_to portfolios_path
    flash[:notice] ="Portfolio Edited Successfully"
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy
    flash[:notice] ="Portfolio Deleted Successfully"
    redirect_to portfolios_path
  end

private

  def portfolio_params
    params.require(:portfolio).permit(:title , :description , :url , :portfolio_image , :image)
  end

end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/portfolios/_portfolio.html.erb
<div class="form-group color-dark-font color-font-black">
    <label for="title">Title:</label>
    <%= f.text_field :title,:class=>"form-control" %>
</div>
<div class="form-group color-dark-font color-font-black">
    <label for="description">Details:</label>
    <%= f.text_field :description,:class=>"form-control"%>
</div>
<div class="form-group color-dark-font color-font-black">
  <label for="url">Youtube Url:</label>
  <%= f.url_field :url,:class=>"form-control"%>
</div>
<div class="form-group color-dark-font color-font-black">
  <label for="image">Image:</label>
  <%= f.url_field :image,:class=>"form-control"%>
</div>

app/views/portfolios/create.html.erb
<h1>Portfolio#create</h1>
<p>Find me in app/views/portfolio/create.html.erb</p>

app/views/portfolios/destroy.html.erb
<h1>Portfolio#destroy</h1>
<p>Find me in app/views/portfolio/destroy.html.erb</p>

app/views/portfolios/edit.html.erb
<div class="container">
  	<div class="row" style="margin-top: 85px;">
	  	<h4 class="modal-title center">Edit Portfolio</h4>
	  	<div class="col-md-3"></div>
	  	<div class="col-md-6 divider_dark divider-dark-color"></div>
	</div>
	    <div class="row">
	    <div class="col-md-3"></div>

		      <div class="col-md-6 color-dark-font color-font-black">
					<%= form_for @portfolio do |f| %>
						<%= render :partial => "portfolio", :locals => { :f => f, :portfolio => @portfolio } %>
						<%= f.submit "Save" , :class => "label-success btn btn-md" %>
					<% end %>
			  </div>
		</div>
  	</div>
<div class="row">
<div class="col-md-3"></div>
    <div class="col-md-6 divider_dark divider-dark-color"></div>
</div>
</div>

app/views/portfolios/index.html.erb
<div class="container">
  <div class="row" style="margin-top: 85px;">
  <h2 class="modal-title center">Portfolios</h2>
    <div class="divider_dark divider-dark-color"></div>
    <div class="row">
      <div class="col-md-12">
        <%= link_to 'New', new_portfolio_path , :class => "label-success btn btn-md" , :style => "float: right;" %>
      </div>
    </div>
    <div class="col-md-12">
    
      <table class="table table-hover">
        <thead class="table" >
          <tr>
            <th>Title</th>
            <th>Details</th>
            <th>Youtube Url</th>
            <th>Image</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Destroy</th>
          </tr>
        </thead>

        <tbody>
          <% @portfolios.each do |portfolio| %>
            <tr>
              <td><%= portfolio.title %></td>
              <td><%= portfolio.description %></td>
              <td><%= portfolio.url %></td>
              <td><%= image_tag portfolio.image, :class => "img_responsive",:style=>"width: 100px;height: 50px;" %></td>
              <td><%= link_to 'Show', portfolio_path(portfolio.id), :class => "label-info btn btn-sm"%>
              </td>
              <td><%= link_to 'Edit', edit_portfolio_path(portfolio), :class => "color btn btn-sm"%></td>
              <td><a href="/portfolios/<%=portfolio.id%>/delete" data-confirm="Are You Sure" data-method="get" class="label-danger btn btn-sm ">Delete</a>
              <%#= link_to 'Destroy', portfolio, 'data-method' => :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %> 
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="divider_dark divider-dark-color"></div>
  </div>
  <!--Pagination-->
  <div class="row top center">
    <div class="col-md-12">
      <ul class="pagination">
        <%= will_paginate @blogs, renderer: BootstrapPagination::Rails%>
      </ul>
    </div>
  </div>
  <!--Pagination-->
</div>

app/views/portfolios/new.html.erb
<div class="container">
  	<div class="row" style="margin-top: 85px;">
	  	<h4 class="modal-title center">New Portfolio</h4>
	  	<div class="col-md-3"></div>
	  	<div class="col-md-6 divider_dark divider-dark-color"></div>
	</div>
    <div class="row">
    <div class="col-md-3"></div>

	      <div class="col-md-6 color-dark-font color-font-black">
				<%= form_for @portfolio do |f| %>
					<%= render :partial => "portfolio", :locals => { :f => f, :portfolio => @portfolio } %>
					<%= f.submit "Save", :class=>"label-success btn btn-md" %>
				<% end %>
		  </div>
	</div>
	<div class="row">
		<div class="col-md-3"></div>
	    <div class="col-md-6 divider_dark divider-dark-color"></div>
	</div>
</div>

</div>

app/views/portfolios/show.html.erb
<div class="container">
  	<div class="row" style="margin-top: 85px;">
	  	<h4 class="modal-title center">Details of Portfolio</h4>
	  	<div class="col-md-3"></div>
	  	<div class="col-md-6 divider_dark divider-dark-color"></div>
	</div>
    <div class="row">
    <div class="col-md-3"></div>

	      <div class="col-md-6 color-dark-font color-font-black">
			<div class="form-group color-dark-font color-font-black">
				<label for="title">Title:</label>
				<%= @portfolio.title %>
			</div>
			<div class="form-group color-dark-font color-font-black">
				<label for="description">Details:</label>
				<%= @portfolio.description %>
			</div>
			<div class="form-group color-dark-font color-font-black">
				<label for="url">Youtube Url:</label>
				<%= @portfolio.url %>
			</div>
			<div class="form-group color-dark-font color-font-black">
				<label for="image">Image:</label>
				<%=image_tag @portfolio.image, :class => "img_responsive" %>
			</div>
			<div class="form-group color-dark-font color-font-black">
				<%=link_to "Back" , portfolios_path , :class => "label-success btn btn-md" %>
			</div>
		  </div>
	</div>
	<div class="row">
		<div class="col-md-3"></div>
	    <div class="col-md-6 divider_dark divider-dark-color"></div>
	</div>
</div>

</div>

app/views/portfolios/update.html.erb
<h1>Portfolio#update</h1>
<p>Find me in app/views/portfolio/update.html.erb</p>