config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions , :portfolios , :contacts

  resources :blogs do
    match '/comments/:id/approve' => 'comments#approve', :as => :approve , via: [:get, :post]
    match '/comments/:id/delete' => 'comments#destroy', via: [:get,:delete]
    resources :comments
  end

  match '/login' => "user_sessions#new",      :as => :login , via: [:get, :post]
  match '/logout' => "user_sessions#destroy", :as => :logout , via: [:get, :post]
  match '/about_us' => 'dashboard#about_us', :as => :about_us , via: [:get, :post]
  match '/homepage' => 'dashboard#homepage', :as => :homepage , via: [:get, :post]
  match '/portfolios/:id/delete' => 'portfolios#destroy', via: [:get]
  match '/blogs/:id/delete' => 'blogs#destroy', via: [:get,:delete]

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup, via: [:get, :post]

  root :to => 'dashboard#homepage'

end

app/models/user.rb
class User < ActiveRecord::Base
	
	acts_as_authentic do |c|
    	c.login_field = 'email'
  	end # block optional

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_user, :only => [:show, :edit, :update]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		
		# Saving without session maintenance to skip
		# auto-login which can't happen here because
		# the User has not yet been activated
		if @user.save
		  flash[:notice] = "Your account has been created."
		  redirect_to signup_url
		else
		  flash[:notice] = "There was a problem creating you."
		  render :action => :new
		end

	end

	def show
		@user = current_user
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user # makes our views "cleaner" and more consistent
		if @user.update_attributes(params[:user])
		  flash[:notice] = "Account updated!"
		  redirect_to account_url
		else
		  render :action => :edit
		end
	end
	
private

		# def user_params
	 #    	params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
	 #  	end
	  	def user_params
		    params.require(:user).permit(:name , :email , :password, :password_confirmation)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
#app/views/users/_form.html.erb

<%= render "shared/error_messages", :target => @user %>

<p>
<%= form.label :name %><br />
<%= form.text_field :name %>
</p>
<p>
<%= form.label :email %><br />
<%= form.text_field :email %>
</p>
<p>
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %>
</p>
<p>
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %>
</p>

app/views/users/new.html.erb
#app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f| %>
<%= render :partial => "form", :object => f, :locals => { :user => @user } %>
<%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
# app/views/users/show.html.erb
<p>
<b>Email:</b>
<%=h @user.email %>
</p>

<p>
<b>Login count:</b>
<%=h @user.login_count %>
</p>

<p>
<b>Last request at:</b>
<%=h @user.last_request_at %>
</p>

<p>
<b>Last login at:</b>
<%=h @user.last_login_at %>
</p>

<p>
<b>Current login at:</b>
<%=h @user.current_login_at %>
</p>

<p>
<b>Last login ip:</b>
<%=h @user.last_login_ip %>
</p>

<p>
<b>Current login ip:</b>
<%=h @user.current_login_ip %>
</p>

<%= link_to 'Edit Account', edit_account_path %>